### PR TITLE
Addresses duplicated main tags on some pages

### PR DESCRIPTION
**Pull request by rthbound**
- Ideally I would remove the lone opening tag from the header file
    and the lone closing tag from the footer file, but it seems most
    pages are depending on those.

### CODE REVIEW

**Comment by Smona** [comment]
Good catch! We need those classes that are on the main class though so we can apply styles for the pages. A `<section>` tag would probably be more semantically correct, right?

Also, please work from https://github.com/politicalrev/political-revolution.com in the future. Totally my bad as I haven't marked this repo as deprecated yet. That new repo has a different file structure but better developer workflow and portability. 

You mind submitting a new pull request on the new one? 💖

**Comment by rthbound** [comment]
Sure, I'll amend this one... rather than removing the main tags, I'll replace with section.

**Comment by rthbound** [comment]
Amended, @Smona!

**Comment by rthbound** [comment]
OH. Different remote entirely... I didn't catch your meaning @Smona. Will do.

**Pull request closed without merging**
